spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:papi}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

    hikari:
      connection-timeout: 30000   # ms
      maximum-pool-size: 5
      max-lifetime: 1800000       # ms
      idle-timeout: 600000        # ms

  jpa:
    hibernate:
      ddl-auto: validate
